steps:
  # install dependencies
  - name: python
    entrypoint: /bin/sh
    args: ["-c", "pip install -r requirements.txt"]
  # run unit tests
  # - name: python
  #   entrypoint: python
  #   args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"]
