steps:
  # run unit tests
  # - name: python
  #   entrypoint: /bin/sh
  #   args: ["-c", "pip install -r requirements.txt && pytest test/test_*.py"]

  # get build number
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: "."
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ["-"]

  - id: "build and submit the dataflow job"
    name: "python:3.11"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        buildNumber=$(cat _BUILDNUMBER) \
        && echo "Build Number is ${buildNumber}" \
        && pip install -r requirements.txt --user \
        && python -m job_search.data.pipeline \
          --project=gcp-practice \
          --runner=DataflowRunner \
          --region=us-central1 \
          --setup_file=./setup.py \
          --temp_location=gs://dataflow-jobsearch-bucket/temp \
          --service_account_email=dmoton3.14@gmail.com
    waitFor: ["get build number"]
