steps:
  - name: "python"
    entrypoint: "python"
    args: ["-m", "pip", "install", "--upgrade", "pip"]
  - name: python
    entrypoint: python
    args:
      [
        "-m",
        "pip",
        "install",
        "build",
        "Requests",
        "pandas",
        "apache_beam[gcp]==2.48.0",
        "jobspy",
        "--user",
      ]
