steps:
  # run unit tests
  # - name: python
  #   entrypoint: /bin/sh
  #   args: ["-c", "pip install -r requirements.txt && pytest test/test_*.py"]

  - id: "build and submit the dataflow job"
    name: "us-central1-docker.pkg.dev/gcp-practice-365607/job-search/job_search:latest"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        pip install apache_beam[gcp] \
        && python job_search/data/pipeline.py \
          --project=gcp-practice-365607 \
          --runner=DataflowRunner \
          --region=us-central1 \
          --setup_file=./setup.py \
          --temp_location=gs://dataflow-jobsearch-bucket/temp \
          --staging_location=gs://dataflow-jobsearch-bucket/staging \
          --service_account_email=dataflow-sa@gcp-practice-365607.iam.gserviceaccount.com
