steps:
  # run unit tests
  # - name: python
  #   entrypoint: /bin/sh
  #   args: ["-c", "pip install -r requirements.txt && pytest test/test_*.py"]

  - id: "build and submit the dataflow job"
    name: "gcr.io/google_appengine/python"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip3 install -r requirements.txt \
        && python3 -m job_search.data.pipeline \
          --project=gcp-practice-365607 \
          --runner=DataflowRunner \
          --region=us-central1 \
          --setup_file=./setup.py \
          --temp_location=gs://dataflow-jobsearch-bucket/temp \
          --service_account_email=dataflow-sa@gcp-practice-365607.iam.gserviceaccount.com
